In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3,4,5])

In [3]:
v-1

array([0, 1, 2, 3, 4])

In [4]:
v*5

array([ 5, 10, 15, 20, 25])

In [5]:
v

array([1, 2, 3, 4, 5])

In [9]:
np.absolute(np.array([-3,-2,-1])) #mutlak değer alan fonks

array([3, 2, 1])

In [17]:
np.sin(30)

-0.9880316240928618

In [22]:
np.log(v) #tüm elemanların logaritmasını al

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [23]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\erkan\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\erkan\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >

In [24]:
np.mean(v)

3.0

In [25]:
np.min(v)

1

5 *x0 + x1 = 12
x0 + 3 * x1 = 10

In [29]:
a = np.array([[5,1], [1,3]])

In [30]:
a

array([[5, 1],
       [1, 3]])

In [31]:
b = np.array([12,10])

In [32]:
x = np.linalg.solve(a,b)

In [33]:
x

array([1.85714286, 2.71428571])

In [37]:
c = np.random.randint(10 size=(3,5))

SyntaxError: invalid syntax (<ipython-input-37-424b1e9f792f>, line 1)

In [38]:
m = np.random.randint(10, size=(3,5))

In [39]:
m

array([[1, 7, 7, 7, 1],
       [2, 3, 5, 7, 9],
       [4, 2, 6, 9, 6]])

In [40]:
m[:2,:3]

array([[1, 7, 7],
       [2, 3, 5]])

In [61]:
n = np.random.randint(10, size=(4,10))

In [62]:
n

array([[4, 9, 4, 7, 5, 2, 2, 9, 7, 0],
       [2, 7, 3, 2, 5, 1, 2, 0, 9, 5],
       [5, 0, 8, 6, 6, 8, 6, 8, 1, 1],
       [2, 7, 5, 5, 4, 3, 2, 7, 2, 4]])

In [60]:
[n[1], n[3]]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [57]:
v[[1,2,3]]

array([2, 3, 4])

In [64]:
v

array([1, 2, 3, 4, 5])

In [63]:
n[0, [1,2]]

array([9, 4])