In [1]:
import numpy as np

In [2]:
a = np.random.randint(10, size=10)

In [3]:
a;

In [4]:
a

array([7, 7, 2, 1, 8, 7, 6, 6, 2, 5])

In [5]:
a[0]

7

In [6]:
a[:3]

array([7, 7, 2])

In [7]:
a[-1]

5

In [8]:
a[0]= 61

In [9]:
a

array([61,  7,  2,  1,  8,  7,  6,  6,  2,  5])

In [11]:
m = np.random.randint(10, size=(3,5))
m

array([[8, 7, 1, 9, 4],
       [5, 6, 0, 0, 8],
       [7, 7, 3, 0, 0]])

In [17]:
m[2,1]

7

In [13]:
m[1,2]

0

In [15]:
m[0,0]

8

In [18]:
m[1,4]

8

In [19]:
b = np.arange(20,30)
b

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
b[:4], b[3:]

(array([20, 21, 22, 23]), array([23, 24, 25, 26, 27, 28, 29]))

In [24]:
b[0::2]

array([20, 22, 24, 26, 28])

In [26]:
c = np.random.randint(100, size=(5,5))
c

array([[10, 44,  9, 73, 10],
       [20, 26, 10, 82, 15],
       [ 1, 83, 48, 94, 11],
       [52, 15, 21, 72, 18],
       [12, 60, 44, 24, 35]])

In [27]:
c[0::2] #0,2,4. indeksteki satırları getirdi

array([[10, 44,  9, 73, 10],
       [ 1, 83, 48, 94, 11],
       [12, 60, 44, 24, 35]])

In [28]:
c[:,0] #0. sütunu getirdi (tüm satırlardaki 0. sütunlar)

array([10, 20,  1, 52, 12])

In [29]:
c[2,1] #2. satır 1. sütun

83

In [30]:
c[:1, 0]

array([10])

In [31]:
c[:3,:3] #3. satıra kadar ve 3. sütüna kadar 

array([[10, 44,  9],
       [20, 26, 10],
       [ 1, 83, 48]])

In [38]:
c[2:,2:]**2 #3. satırdan sonrası ve 3. sütundan sonrası VE KARESİNİ ALDIK

array([[2304, 8836,  121],
       [ 441, 5184,  324],
       [1936,  576, 1225]], dtype=int32)

In [40]:
c[3,3] #4. satır, 4. sütundaki eleman

72

In [42]:
c[3:4, 3:4] #c[3,3] teki işlemin aslında aynısı

array([[72]])

In [47]:

d= c[0,:],c[4,:]

In [45]:
c

array([[10, 44,  9, 73, 10],
       [20, 26, 10, 82, 15],
       [ 1, 83, 48, 94, 11],
       [52, 15, 21, 72, 18],
       [12, 60, 44, 24, 35]])

In [48]:
d

(array([10, 44,  9, 73, 10]), array([12, 60, 44, 24, 35]))

In [55]:
d= [c[0,:] , c[4,:]]

In [56]:
d

[array([10, 44,  9, 73, 10]), array([12, 60, 44, 24, 35])]

In [57]:
c

array([[10, 44,  9, 73, 10],
       [20, 26, 10, 82, 15],
       [ 1, 83, 48, 94, 11],
       [52, 15, 21, 72, 18],
       [12, 60, 44, 24, 35]])

In [61]:
alt_c = c[:2, :2].copy()  #copy fonksiyonu alt matriste yapacağımız işlemin ana matrisi etkilememesini sağlar

In [62]:
alt_c

array([[10, 44],
       [20, 26]])

In [64]:
alt_c**2

array([[ 100, 1936],
       [ 400,  676]], dtype=int32)

In [65]:
c #c matrisi değişmedi

array([[10, 44,  9, 73, 10],
       [20, 26, 10, 82, 15],
       [ 1, 83, 48, 94, 11],
       [52, 15, 21, 72, 18],
       [12, 60, 44, 24, 35]])

In [66]:
v = np.arange(0,30,3) #0dan 30a kadar 3er 3er artan vektör
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [67]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [68]:
al_getir = [1,3,5]

In [69]:
v[al_getir] #1. index 3. index 5. indexi getirdi

array([ 3,  9, 15])

In [70]:
c

array([[10, 44,  9, 73, 10],
       [20, 26, 10, 82, 15],
       [ 1, 83, 48, 94, 11],
       [52, 15, 21, 72, 18],
       [12, 60, 44, 24, 35]])

In [81]:
satir = np.array([0,1,2])
satir

array([0, 1, 2])

In [82]:
sutun = np.array([0,1,2])
sutun

array([0, 1, 2])

In [83]:
c[satir,sutun]

array([10, 26, 48])

In [2]:
import numpy as np

c = np.random.randint(100, size=(5,5))

In [3]:
c

array([[ 6,  8, 12,  2, 22],
       [ 6, 14, 63, 73, 41],
       [17, 94,  1,  8, 30],
       [39, 29, 76, 86, 37],
       [82,  3, 41, 95, 33]])

In [4]:
c[[0,4]]


array([[ 6,  8, 12,  2, 22],
       [82,  3, 41, 95, 33]])

In [5]:
c[0,4]

22