In [1]:
import numpy as np

# özellikleri

ndim: boyut sayısı
shape: boyut bilgisi
size: toplam eleman sayısı
dtype: array veri tipi

In [33]:
np.random.randint(10, size=(5,2,3))  #size sonrası adet, satır, sütun

array([[[9, 1, 7],
        [4, 1, 7]],

       [[1, 2, 1],
        [0, 7, 1]],

       [[3, 8, 9],
        [4, 9, 5]],

       [[6, 8, 3],
        [5, 1, 1]],

       [[3, 7, 9],
        [1, 5, 9]]])

In [3]:
np.random.randint(9, size=10)

array([1, 8, 0, 7, 1, 1, 1, 8, 4, 8])

In [5]:
np.random.randint(5, size=10) #5'e kadar rakamlardan oluşan 10 elemanlı

array([0, 1, 0, 4, 0, 4, 0, 2, 1, 1])

In [9]:
a = np.random.randint(10, size=10)

In [10]:
a.ndim

1

In [11]:
a.shape

(10,)

In [13]:
a.size

10

In [14]:
a.dtype

dtype('int32')

In [17]:
b=np.random.randint(10, size=(3,5))

In [18]:
b

array([[4, 3, 3, 9, 7],
       [1, 9, 7, 6, 7],
       [4, 6, 6, 4, 3]])

In [19]:
b.shape

(3, 5)

In [20]:
b.size

15

In [21]:
b.ndim

2

In [31]:
5 * np.arange(1,10)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [32]:
5 * np.arange(1,10).reshape((3,3))

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
a

array([8, 1, 1, 3, 1, 8, 7, 6, 8, 7])

In [41]:
x = np.array=[(3,1)]

In [42]:
x

[(3, 1)]

In [43]:
a.ndim

1