# Neden Numpy

In [7]:
import numpy as np

In [9]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [10]:
a*b

array([ 2,  6, 12, 20])

In [11]:
a+b

array([3, 5, 7, 9])

In [12]:
a/b

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [13]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [14]:
(a**3)/b

array([ 0.5       ,  2.66666667,  6.75      , 12.8       ])

In [25]:
matris = np.array([1,2,3,4], [5,6,7,8], [9,10,11,12])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [17]:

text = [[4, 3, 8, 9, 5, 1, 2, 7, 6], [8, 3, 4, 1, 5, 9, 6, 7, 2],
[6, 1, 8, 7, 5, 3, 2, 9, 4], [6, 9, 8, 7, 5, 3, 2, 1, 4],
[6, 1, 8, 7, 5, 3, 2, 1, 4], [6, 1, 3, 2, 9, 4, 8, 7, 5]]

text = np.array(text)

print text[0].reshape((3, 3))
print text[1].reshape((3, 3))

SyntaxError: invalid syntax (<ipython-input-17-bf174845ae39>, line 7)

In [28]:
import numpy as np

text = [[4, 3, 8, 9, 5, 1, 2, 7, 6], [8, 3, 4, 1, 5, 9, 6, 7, 2],
[6, 1, 8, 7, 5, 3, 2, 9, 4], [6, 9, 8, 7, 5, 3, 2, 1, 4],
[6, 1, 8, 7, 5, 3, 2, 1, 4], [6, 1, 3, 2, 9, 4, 8, 7, 5]]

text = np.array(text)



In [30]:
print(text[0])

[4 3 8 9 5 1 2 7 6]


In [31]:
np.array([1,2,3])

array([1, 2, 3])

In [32]:
a = np.array([1,2,3,4])

In [33]:
a

array([1, 2, 3, 4])

In [36]:
np.array([3.14, 4, 2, 13], dtype=("int"))

array([ 3,  4,  2, 13])

In [37]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
np.zeros(10, dtype =("int"))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [40]:
np.ones((3,5), dtype= ("int"))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [46]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [47]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [56]:
np.full((3,5), 61)

array([[61, 61, 61, 61, 61],
       [61, 61, 61, 61, 61],
       [61, 61, 61, 61, 61]])

In [60]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [69]:
np.random.normal(10,4, (4,4))

array([[12.2154889 ,  8.47798995,  9.80217892, 11.7994794 ],
       [10.49360103,  8.04098714,  6.13700363,  7.45871657],
       [13.27376479,  8.87740147,  9.46572391,  8.52532078],
       [ 8.00275228, 12.48387557, 10.23546261,  9.72250988]])