In [1]:
import pandas as pd

In [2]:
import numpy as np

In [25]:
matris = np.arange(1,10).reshape((3,3))

In [26]:
matris

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
pd.DataFrame(matris, columns=["sutun1", "sutun2", "sutun3"], index= ["a","b","c"], dtype="float")

sutun1  sutun2  sutun3
a     1.0     2.0     3.0
b     4.0     5.0     6.0
c     7.0     8.0     9.0

In [37]:
matris[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [39]:
matris[[1,2]]

array([[4, 5, 6],
       [7, 8, 9]])

In [40]:
df = pd.DataFrame(matris, columns=["sutun1", "sutun2", "sutun3"], index= ["a","b","c"], dtype="float")

In [41]:
df

sutun1  sutun2  sutun3
a     1.0     2.0     3.0
b     4.0     5.0     6.0
c     7.0     8.0     9.0

In [42]:
df["a":"b"]

sutun1  sutun2  sutun3
a     1.0     2.0     3.0
b     4.0     5.0     6.0

In [50]:
np.arange(1,26).reshape((5,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [61]:
c = np.random.randint(100, size=(5,5))
c

array([[84, 46, 19, 42, 18],
       [43, 37, 49, 24, 63],
       [73,  6, 45, 34, 49],
       [24, 62,  1, 73, 62],
       [97, 39, 19, 29, 14]])

In [65]:
df = pd.DataFrame(c)

In [66]:
df

0   1   2   3   4
0  84  46  19  42  18
1  43  37  49  24  63
2  73   6  45  34  49
3  24  62   1  73  62
4  97  39  19  29  14

In [68]:
df.drop(1, axis=0) # 1. indexi sildik ama kalıcı değil

0   1   2   3   4
0  84  46  19  42  18
2  73   6  45  34  49
3  24  62   1  73  62
4  97  39  19  29  14

In [69]:
df

0   1   2   3   4
0  84  46  19  42  18
1  43  37  49  24  63
2  73   6  45  34  49
3  24  62   1  73  62
4  97  39  19  29  14

In [70]:
df.drop(1, axis=0, inplace = True) #1. index kalıcı olarak silindi

In [71]:
df

0   1   2   3   4
0  84  46  19  42  18
2  73   6  45  34  49
3  24  62   1  73  62
4  97  39  19  29  14

In [26]:
c = np.random.randint(100, size=(5,5))
c

array([[10, 44,  9, 73, 10],
       [20, 26, 10, 82, 15],
       [ 1, 83, 48, 94, 11],
       [52, 15, 21, 72, 18],
       [12, 60, 44, 24, 35]])

In [73]:
c = pd.DataFrame(c)

In [77]:
c.drop(2, axis=1)

0   1   3   4
0  84  46  42  18
1  43  37  24  63
2  73   6  34  49
3  24  62  73  62
4  97  39  29  14

In [81]:
l = [3,4]
l

[3, 4]

In [82]:
c.drop(l, axis=1)

0   1   2
0  84  46  19
1  43  37  49
2  73   6  45
3  24  62   1
4  97  39  19

In [83]:
c.drop(l, axis=0)

0   1   2   3   4
0  84  46  19  42  18
1  43  37  49  24  63
2  73   6  45  34  49

In [84]:
df

0   1   2   3   4
0  84  46  19  42  18
2  73   6  45  34  49
3  24  62   1  73  62
4  97  39  19  29  14

In [98]:
df1=np.random.randint(101, size= (5,5))

In [99]:
df1= pd.DataFrame(df1, columns=["degisken1", "degisken2", "degisken3", "degisken4", "degisken5"],
                               index= ["a","b","c","d","e"])

In [100]:
df1

degisken1  degisken2  degisken3  degisken4  degisken5
a         71         72         25         72         92
b         99         27         18         23         15
c         98         98          7         73         78
d         70         13         30         97         74
e          5         74         53         48         76

In [102]:
df1["degisken5"] 

a    92
b    15
c    78
d    74
e    76
Name: degisken5, dtype: int32

In [103]:
df1["degisken5"]= [1,2,3,4,5]

In [104]:
df1["degisken5"] 

a    1
b    2
c    3
d    4
e    5
Name: degisken5, dtype: int64

In [105]:
df1

degisken1  degisken2  degisken3  degisken4  degisken5
a         71         72         25         72          1
b         99         27         18         23          2
c         98         98          7         73          3
d         70         13         30         97          4
e          5         74         53         48          5

In [106]:
df1["degisken6"] = df1["degisken1"] * df1["degisken3"]

In [107]:
df1

degisken1  degisken2  degisken3  degisken4  degisken5  degisken6
a         71         72         25         72          1       1775
b         99         27         18         23          2       1782
c         98         98          7         73          3        686
d         70         13         30         97          4       2100
e          5         74         53         48          5        265

In [121]:
df1.loc["d":"e"] #tanımlandığı şekli ile seçim yapmak için kullanılır

degisken1  degisken2  degisken3  degisken4  degisken5  degisken6
d         70         13         30         97          4       2100
e          5         74         53         48          5        265

In [124]:
df1.iloc[0:3] #bildigimiz indexleme işlemi

degisken1  degisken2  degisken3  degisken4  degisken5  degisken6
a         71         72         25         72          1       1775
b         99         27         18         23          2       1782
c         98         98          7         73          3        686

In [126]:
df1.iloc[0,:]

degisken1      71
degisken2      72
degisken3      25
degisken4      72
degisken5       1
degisken6    1775
Name: a, dtype: int64

In [132]:
df1.iloc[[0,4]]["degisken3"] #0. ve 4. index ve degisken3 sütunu

a    25
e    53
Name: degisken3, dtype: int32